

from libgitlet import ref_create
from src.objects.commit import GitCommit
from src.objects.objects import object_find, object_write


class GitTag(GitCommit):
    fmt = b'tag'
    
def tag_create(repo, name, ref, create_tag_object=False):
    sha = object_find(repo, ref)
    
    if create_tag_object:
        tag = GitTag()
        tag.kvlm = dict()
        tag.kvlm[b'object'] = sha.encode()
        tag.kvlm[b'type'] = b'commit'
        tag.kvlm[b'tag'] = name.encode()
        tag.kvlm[b'tagger'] = b'Gitlet <gitlet@example.com>'
        tag.kvlm[None] = b"A tag generated by gitlet, which won't let you customize the message!\n"
        
        tag_sha = object_write(tag,repo)
        
        ref_create(repo,"tags/"+name,tag_sha)
        
    else:
        ref_create(repo,"tags/" + name,sha)